# Generated by Django 2.2.2 on 2019-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=800, null=True, verbose_name='(URL)别名'),
        ),
    ]
