# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-03 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgenization', '0003_auto_20190603_1425'),
        ('courses', '0002_auto_20190601_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgenization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
