# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190530_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userporfile',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userporfile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userporfile',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userporfile',
            name='moblie',
            field=models.CharField(max_length=11, null=True, verbose_name='手机'),
        ),
    ]
